import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RTKProvider from "@/redux/provider";
import {
  AdminHeaderWrapper,
  HomeHeaderWrapper,
} from "@/components/re-usable/header-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RTKProvider>
          <AdminHeaderWrapper />
          <HomeHeaderWrapper />
          {children}
        </RTKProvider>
      </body>
    </html>
  );
}
